project_id = "mbryndcvumhfjgmogifs"

[functions.minio-test]
verify_jwt = false

[functions.minio-upload]
verify_jwt = false

[functions.minio-delete]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.pixel-event]
verify_jwt = false

[functions.form-public-save]
verify_jwt = false

[functions.google-oauth-start]
verify_jwt = false

[functions.google-oauth-callback]
verify_jwt = false

[functions.google-sheets-sync]
verify_jwt = false