import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    fontFamily: {
      sans: ["'Borna'", "ui-sans-serif", "system-ui", "sans-serif"],
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        // TwoBrain Brand Colors
        tb: {
          text: {
            primary: "hsl(var(--tb-text-primary))",
            secondary: "hsl(var(--tb-text-secondary))",
            muted: "hsl(var(--tb-text-muted))",
            light: "hsl(var(--tb-text-light))",
          },
          bg: {
            page: "hsl(var(--tb-bg-page))",
            sidebar: "hsl(var(--tb-bg-sidebar))",
            hover: "hsl(var(--tb-bg-hover))",
            surface: "hsl(var(--tb-bg-surface))",
          },
          accent: {
            DEFAULT: "hsl(var(--tb-accent))",
            dark: "hsl(var(--tb-accent-dark))",
            focus: "hsl(var(--tb-accent-focus))",
          },
          border: {
            input: "hsl(var(--tb-input-border))",
            card: "hsl(var(--tb-card-border))",
          },
          icon: {
            muted: "hsl(var(--tb-icon-muted))",
          },
        },
        paper: {
          DEFAULT: "hsl(var(--paper))",
          foreground: "hsl(var(--paper-foreground))",
          50: "hsl(var(--paper-50))",
          100: "hsl(var(--paper-100))",
          200: "hsl(var(--paper-200))",
          300: "hsl(var(--paper-300))",
          400: "hsl(var(--paper-400))",
          500: "hsl(var(--paper-500))",
          600: "hsl(var(--paper-600))",
          700: "hsl(var(--paper-700))",
          800: "hsl(var(--paper-800))",
          900: "hsl(var(--paper-900))",
          950: "hsl(var(--paper-950))",
          1000: "hsl(var(--paper-1000))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
          muted: "hsl(var(--sidebar-muted))",
          hover: "hsl(var(--sidebar-hover))",
        },
        green: {
          100: "hsl(var(--green-100))",
          200: "hsl(var(--green-200))",
          300: "hsl(var(--green-300))",
          400: "hsl(var(--green-400))",
          500: "hsl(var(--green-500))",
          600: "hsl(var(--green-600))",
          700: "hsl(var(--green-700))",
          800: "hsl(var(--green-800))",
          900: "hsl(var(--green-900))",
          950: "hsl(var(--green-950))",
          1000: "hsl(var(--green-1000))",
        },
        gray: {
          50: "hsl(var(--gray-50))",
          100: "hsl(var(--gray-100))",
          200: "hsl(var(--gray-200))",
          300: "hsl(var(--gray-300))",
          400: "hsl(var(--gray-400))",
          500: "hsl(var(--gray-500))",
          600: "hsl(var(--gray-600))",
          700: "hsl(var(--gray-700))",
          800: "hsl(var(--gray-800))",
          900: "hsl(var(--gray-900))",
          950: "hsl(var(--gray-950))",
        },
        lime: {
          dark: "hsl(var(--green-1000))",
        },
        node: {
          contact: "hsl(var(--node-contact))",
          "contact-accent": "hsl(var(--node-contact-accent))",
          text: "hsl(var(--node-text))",
          "text-accent": "hsl(var(--node-text-accent))",
          choice: "hsl(var(--node-choice))",
          "choice-accent": "hsl(var(--node-choice-accent))",
          rating: "hsl(var(--node-rating))",
          "rating-accent": "hsl(var(--node-rating-accent))",
          other: "hsl(var(--node-other))",
          "other-accent": "hsl(var(--node-other-accent))",
          condition: "hsl(var(--node-condition))",
          "condition-accent": "hsl(var(--node-condition-accent))",
          "variable-op": "hsl(var(--node-variable-op))",
          "variable-op-accent": "hsl(var(--node-variable-op-accent))",
          ending: "hsl(var(--node-ending))",
          "ending-accent": "hsl(var(--node-ending-accent))",
          integration: "hsl(var(--node-integration))",
          "integration-accent": "hsl(var(--node-integration-accent))",
          webhook: "hsl(var(--node-webhook))",
          "webhook-accent": "hsl(var(--node-webhook-accent))",
          analytics: "hsl(var(--node-analytics))",
          "analytics-accent": "hsl(var(--node-analytics-accent))",
          whatsapp: "hsl(var(--node-whatsapp))",
          "whatsapp-accent": "hsl(var(--node-whatsapp-accent))",
          email: "hsl(var(--node-email))",
          "email-accent": "hsl(var(--node-email-accent))",
          abtest: "hsl(var(--node-abtest))",
          "abtest-accent": "hsl(var(--node-abtest-accent))",
          wait: "hsl(var(--node-wait))",
          "wait-accent": "hsl(var(--node-wait-accent))",
          jump: "hsl(var(--node-jump))",
          "jump-accent": "hsl(var(--node-jump-accent))",
          ai: "hsl(var(--node-ai))",
          "ai-accent": "hsl(var(--node-ai-accent))",
          imagegen: "hsl(var(--node-imagegen))",
          "imagegen-accent": "hsl(var(--node-imagegen-accent))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
